/* This file is automatically generated by gensymlist.sh. DO NOT EDIT! */
/*
 *  GRUB  --  GRand Unified Bootloader
 *  Copyright (C) 2005,2007  Free Software Foundation, Inc.
 *
 *  GRUB is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation, either version 3 of the License, or
 *  (at your option) any later version.
 *
 *  GRUB is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License
 *  along with GRUB.  If not, see <http://www.gnu.org/licenses/>.
 */

void grub_init_all (void);
void grub_fini_all (void);
void grub_affs_init (void);
void grub_tar_init (void);
void grub_cpio_init (void);
void grub_fat_init (void);
void grub_ext2_init (void);
void grub_hfs_init (void);
void grub_hfsplus_init (void);
void grub_iso9660_init (void);
void grub_udf_init (void);
void grub_jfs_init (void);
void grub_minix_init (void);
void grub_ntfs_init (void);
void grub_ntfscomp_init (void);
void grub_reiserfs_init (void);
void grub_sfs_init (void);
void grub_ufs2_init (void);
void grub_ufs1_init (void);
void grub_xfs_init (void);
void grub_befs_be_init (void);
void grub_befs_init (void);
void grub_afs_be_init (void);
void grub_afs_init (void);
void grub_pc_partition_map_init (void);
void grub_apple_partition_map_init (void);
void grub_sun_partition_map_init (void);
void grub_gpt_partition_map_init (void);
void grub_raid_init (void);
void grub_mdraid_init (void);
void grub_lvm_init (void);
void grub_affs_fini (void);
void grub_tar_fini (void);
void grub_cpio_fini (void);
void grub_fat_fini (void);
void grub_ext2_fini (void);
void grub_hfs_fini (void);
void grub_hfsplus_fini (void);
void grub_iso9660_fini (void);
void grub_udf_fini (void);
void grub_jfs_fini (void);
void grub_minix_fini (void);
void grub_ntfs_fini (void);
void grub_ntfscomp_fini (void);
void grub_reiserfs_fini (void);
void grub_sfs_fini (void);
void grub_ufs2_fini (void);
void grub_ufs1_fini (void);
void grub_xfs_fini (void);
void grub_befs_be_fini (void);
void grub_befs_fini (void);
void grub_afs_be_fini (void);
void grub_afs_fini (void);
void grub_pc_partition_map_fini (void);
void grub_apple_partition_map_fini (void);
void grub_sun_partition_map_fini (void);
void grub_gpt_partition_map_fini (void);
void grub_raid_fini (void);
void grub_mdraid_fini (void);
void grub_lvm_fini (void);
